#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".
#   - Agent-synthesized: project matches both `compose` and `react-next` catalog
#     entries (docker-compose.yml + next.config.mjs + package.json with next dep).
#     Multi-match triggers agent fallback (D-05/D-06). The compose catalog entry
#     pattern wins: docker-compose.yml owns the full stack (postgres + redis + app),
#     the app service command handles migrate -> seed -> `npm run dev`, the app port
#     is published 3000:3000. EXEC_CMD is `docker compose up --build`; compose
#     itself handles orchestration and signals.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two `docker compose up --build`
# trees racing in one sandbox. Second invocation exits 0 quietly: the first
# boot is authoritative and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# Researcher resolved log destination: /tmp/pivota-dev.log (always writable,
# matches existing convention). SSE chat panel sees output live AND a file
# exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Compose services control their own bind addresses via the `ports:` block in
# the compose file — there is no env-var lever the wrapper can pull to force
# 0.0.0.0 binding for child containers. The wrapper preamble's per-stack env
# block is intentionally minimal for this compose-based entry.
#
# The app service in docker-compose.yml already runs:
#   next dev -H 0.0.0.0  (via `npm run dev` which uses `next dev -H 0.0.0.0`)
# and the port is published 3000:3000 — sandbox localhost reaches the preview.
#
# ANTHROPIC_API_KEY is injected from the sandbox environment (platform-provided
# via compose `environment: ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}`).
# No wrapper-level env exports needed beyond what compose already handles.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# This project uses .env.local / .env.local.example (Next.js convention).
# Seed .env.local from .env.local.example for first boot, but NEVER let a
# placeholder shadow a variable the platform already injected into the sandbox
# environment. Any KEY already set in the environment is dropped from the copy.
if [[ ! -f .env.local && -f .env.local.example ]]; then
  echo "[pivota] seeding .env.local from .env.local.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: sanitize the copied assignment. Strip unquoted inline # comments.
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    # Replace CHANGE_ME placeholder secrets with generated values.
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.local.example > .env.local
fi

# === Optional pre-exec snippet ===
# No heavyweight one-time installs needed — compose handles the app image build.
# No vite overlay needed (not a Vite project). No JDK/rustup install needed.

# === D-12: idempotent install via lockfile hash + presence check ===
# For a compose-based project, there is no host-side npm install step —
# the app image build (`docker compose up --build`) installs inside the container.
# LOCK_FILE and INSTALL_CMD are empty; the sentinel branch short-circuits.
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH=""
INSTALL_PRESENCE_CHECK=""
INSTALL_CMD=""

# No lockfile to compare; no host-side install needed.
# (docker compose up --build handles image builds including npm ci inside the container.)

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Final-attempt exit code propagates the INNER command's exit code, not a
# fixed 1, so the caller (platform / Daytona) can distinguish "wrapper bug"
# from "user command failed with N".
EXEC_CMD='docker compose up --build'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
