import { generateXlsx, generateDocx } from '@/server/artifacts/artifactGenerator';

export interface OpportunitySummaryData {
  projectId: string;
  productName: string;
  customerName: string;
  applicationArea: string;
  rfqReference: string;
  bidRecommendation: 'Bid' | 'No-Bid' | 'Conditional Bid';
  recommendationRationale: string;
  keyStrengths: string[];
  keyRisks: string[];
  exportControlStatus: string;
  nextActions: string;
}

export interface GapMatrixRow {
  capabilityId: string;
  capabilityArea: string;
  matchLevel: 'High' | 'Medium' | 'Low' | 'Gap';
  evidence: string;
  risk: 'Low' | 'Medium' | 'High' | 'Critical';
  recommendedAction: string;
}

export async function generateOpportunitySummary(
  data: OpportunitySummaryData,
  phaseId: number = 0
): Promise<{ artifactId: string; storageUri: string }> {
  const content = `# Opportunity Summary and Bid/No-Bid Recommendation

**Project:** ${data.projectId} | **Product:** ${data.productName}
**Customer:** ${data.customerName} | **Application:** ${data.applicationArea}
**RFQ Reference:** ${data.rfqReference}

## AI Recommendation: ${data.bidRecommendation}
*Advisory Only — Human Decision Required*

${data.recommendationRationale}

## Key Strengths
${data.keyStrengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

## Key Risks
${data.keyRisks.map((r, i) => `${i + 1}. ${r}`).join('\n')}

## Export/Security Assessment
${data.exportControlStatus}

## Recommended Next Actions
${data.nextActions}

---
*This document is a draft generated by the TT Engineering Copilot AI. It is advisory only.
All bid/no-bid decisions require authorized human approval.*`;

  return generateDocx(content, 'phase0-opportunity-summary.txt', phaseId, 0, 'bid-no-bid-copilot');
}

export async function generateCapabilityGapMatrix(
  rows: GapMatrixRow[],
  phaseId: number = 0
): Promise<{ artifactId: string; storageUri: string; rowCount: number }> {
  const xlsxRows = rows.map(r => ({
    'Capability ID': r.capabilityId,
    'Capability Area': r.capabilityArea,
    'Match Level': r.matchLevel,
    'Evidence': r.evidence,
    'Risk': r.risk,
    'Recommended Action': r.recommendedAction,
  }));

  return generateXlsx(xlsxRows, 'phase0-capability-gap-matrix.xlsx', phaseId, 0, 'bid-no-bid-copilot');
}
