'use client';
import useSWR from 'swr';
import { Download, FileText, Clock, FlaskConical } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { StatusPill } from '@/components/ui/status-pill';
import { Callout } from '@/components/ui/callout';
import { ButtonAnchor } from '@/components/ui/button-link';
import { Skeleton } from '@/components/ui/skeleton';
import { EmptyState } from '@/components/ui/empty-state';
import { DataTable, THead, TH, TBody, TR, TD } from '@/components/ui/data-table';
import { formatDateTime, isoOf } from '@/lib/format';
import { POC_STD_LABEL } from '@/server/tools/evinvPocStd001';

const fetcher = (url: string) => fetch(url).then(r => r.json());

/** The synthetic-data disclaimer. Always first, always visible. */
function SyntheticDisclaimer() {
  return (
    <Callout tone="neutral" icon={FlaskConical}>
      {POC_STD_LABEL} — Synthetic POC Data. Not TT Electronics Product Data. Not for Design, Fabrication, Certification, Procurement, or Production.
    </Callout>
  );
}

export function ArtifactViewer({ artifactId }: { artifactId: string }) {
  const { data: artifact } = useSWR(`/api/artifacts/${artifactId}`, fetcher);
  const { data: versions } = useSWR(`/api/artifacts/${artifactId}/versions`, fetcher);

  if (!artifact || artifact.error) {
    return (
      <div className="space-y-4" data-testid={`artifact-viewer-${artifactId}`}>
        <SyntheticDisclaimer />
        {artifact ? (
          <Card>
            <EmptyState
              icon={FileText}
              title="Artifact not found"
              description="This artifact id doesn't match anything in the project store. It may have been superseded by a newer version."
            />
          </Card>
        ) : (
          <Card>
            <CardContent className="space-y-3">
              <Skeleton className="h-3 w-52" />
              <Skeleton className="h-3 w-full" />
              <Skeleton className="h-3 w-2/3" />
            </CardContent>
          </Card>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-4" data-testid={`artifact-viewer-${artifactId}`}>
      <SyntheticDisclaimer />

      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-start justify-between gap-2">
            <div className="flex min-w-0 items-center gap-2">
              <FileText size={15} strokeWidth={2} className="shrink-0 text-fg-muted" />
              <CardTitle>{artifact.artifactName}</CardTitle>
            </div>
            <div className="flex shrink-0 items-center gap-1.5">
              <StatusPill tone="neutral" size="sm">{artifact.artifactType}</StatusPill>
              <StatusPill tone="neutral" size="sm">v{artifact.version}</StatusPill>
              {artifact.disclaimerPresent && (
                <StatusPill tone="neutral" size="sm">Synthetic POC</StatusPill>
              )}
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* Provenance */}
          <dl className="grid grid-cols-2 gap-x-6 gap-y-2.5 border-t border-line pt-3 text-[12.5px] sm:grid-cols-3">
            <Field label="Phase">Phase {artifact.phaseId}</Field>
            <Field label="Gate">Gate {artifact.gateId}</Field>
            <Field label="Source">{artifact.source}</Field>
            <Field label="Generated by">{artifact.generatedBy}</Field>
            {artifact.rowCount && <Field label="Rows">{artifact.rowCount}</Field>}
            {artifact.pageCount && <Field label="Pages">~{artifact.pageCount}</Field>}
          </dl>

          <ButtonAnchor
            size="sm"
            href={`/api/artifacts/${artifactId}/download`}
            download
            data-testid={`download-artifact-${artifactId}`}
          >
            <Download size={13} strokeWidth={2} />
            Download {artifact.artifactType}
          </ButtonAnchor>
        </CardContent>
      </Card>

      {/* Version history */}
      {(versions?.versions?.length ?? 0) > 1 && (
        <Card className="py-0">
          <CardHeader className="border-b border-line py-3">
            <CardTitle className="flex items-center gap-2">
              <Clock size={14} strokeWidth={2} className="text-fg-muted" />
              Version history
            </CardTitle>
          </CardHeader>
          <DataTable data-testid="artifact-version-history">
            <THead>
              <tr>
                <TH className="w-[80px]">Version</TH>
                <TH className="w-[90px]">Type</TH>
                <TH>Generated</TH>
                <TH className="w-[110px]">Status</TH>
              </tr>
            </THead>
            <TBody>
              {versions.versions.map((v: any) => (
                <TR key={v.artifactId} interactive>
                  <TD className="font-mono text-[11.5px] text-fg">v{v.version}</TD>
                  <TD className="font-mono text-[11.5px]">{v.artifactType}</TD>
                  <TD className="text-[11.5px] whitespace-nowrap text-fg-muted">
                    <time dateTime={isoOf(v.timestamp)}>{formatDateTime(v.timestamp)}</time>
                  </TD>
                  <TD>
                    {v.artifactId === artifactId ? (
                      <StatusPill tone="pass" dot size="sm">Active</StatusPill>
                    ) : (
                      <StatusPill tone="neutral" size="sm">Historical</StatusPill>
                    )}
                  </TD>
                </TR>
              ))}
            </TBody>
          </DataTable>
        </Card>
      )}
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="min-w-0">
      <dt className="text-[10.5px] font-semibold tracking-[0.07em] text-fg-muted uppercase">
        {label}
      </dt>
      <dd className="mt-0.5 truncate text-fg">{children}</dd>
    </div>
  );
}
