'use client';
import useSWR from 'swr';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Download, FileText, Clock } from 'lucide-react';
import { POC_STD_LABEL } from '@/server/tools/evinvPocStd001';

const fetcher = (url: string) => fetch(url).then(r => r.json());

export function ArtifactViewer({ artifactId }: { artifactId: string }) {
  const { data: artifact } = useSWR(`/api/artifacts/${artifactId}`, fetcher);
  const { data: versions } = useSWR(`/api/artifacts/${artifactId}/versions`, fetcher);

  if (!artifact || artifact.error) {
    return (
      <div className="space-y-4" data-testid={`artifact-viewer-${artifactId}`}>
        {/* Synthetic disclaimer — always first, always visible */}
        <div className="rounded-md bg-violet-500/5 border border-violet-500/20 px-3 py-2 text-xs text-violet-400">
          {POC_STD_LABEL} — Synthetic POC Data. Not TT Electronics Product Data. Not for Design, Fabrication, Certification, Procurement, or Production.
        </div>
        <div className="text-sm text-[var(--color-text-muted)]">
          {artifact ? 'Artifact not found.' : 'Loading artifact...'}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4" data-testid={`artifact-viewer-${artifactId}`}>
      {/* Synthetic disclaimer — always first, always visible */}
      <div className="rounded-md bg-violet-500/5 border border-violet-500/20 px-3 py-2 text-xs text-violet-400">
        {POC_STD_LABEL} — Synthetic POC Data. Not TT Electronics Product Data. Not for Design, Fabrication, Certification, Procurement, or Production.
      </div>

      <Card className="bg-[var(--color-surface)] border-[var(--color-border)]">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText size={16} className="text-[var(--color-text-muted)]" />
              <CardTitle className="text-sm">{artifact.artifactName}</CardTitle>
            </div>
            <div className="flex items-center gap-2">
              <Badge className="text-xs bg-blue-500/10 text-blue-400 border border-blue-500/20">
                {artifact.artifactType}
              </Badge>
              <Badge className="text-xs bg-slate-500/10 text-slate-400 border border-slate-500/20">
                v{artifact.version}
              </Badge>
              {artifact.disclaimerPresent && (
                <Badge className="text-xs bg-violet-500/10 text-violet-400 border border-violet-500/20">
                  Synthetic POC
                </Badge>
              )}
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-3">
          {/* Provenance */}
          <div className="grid grid-cols-3 gap-3 text-xs text-[var(--color-text-muted)]">
            <div>Phase: <span className="text-[var(--color-text-primary)]">Phase {artifact.phaseId}</span></div>
            <div>Gate: <span className="text-[var(--color-text-primary)]">Gate {artifact.gateId}</span></div>
            <div>Source: <span className="text-[var(--color-text-primary)]">{artifact.source}</span></div>
            <div>Generated by: <span className="text-[var(--color-text-primary)]">{artifact.generatedBy}</span></div>
            {artifact.rowCount && <div>Rows: <span className="text-[var(--color-text-primary)]">{artifact.rowCount}</span></div>}
            {artifact.pageCount && <div>Pages: <span className="text-[var(--color-text-primary)]">~{artifact.pageCount}</span></div>}
          </div>

          {/* Download control */}
          <a
            href={`/api/artifacts/${artifactId}/download`}
            download
            data-testid={`download-artifact-${artifactId}`}
            className="inline-flex items-center gap-1 rounded-lg border border-[var(--color-border)] bg-transparent px-2.5 py-1.5 text-xs font-medium hover:bg-white/5 transition-colors"
          >
            <Download size={12} />
            Download {artifact.artifactType}
          </a>
        </CardContent>
      </Card>

      {/* Version history */}
      {(versions?.versions?.length ?? 0) > 1 && (
        <Card className="bg-[var(--color-surface)] border-[var(--color-border)]">
          <CardHeader>
            <CardTitle className="text-sm flex items-center gap-2">
              <Clock size={14} />
              Version History
            </CardTitle>
          </CardHeader>
          <CardContent>
            <table className="w-full text-xs" data-testid="artifact-version-history">
              <thead>
                <tr className="border-b border-[var(--color-border)]">
                  {['Version', 'Type', 'Generated', 'Status'].map(h => (
                    <th key={h} className="text-left py-1.5 px-2 text-[var(--color-text-muted)]">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {versions.versions.map((v: any) => (
                  <tr key={v.artifactId} className="border-b border-[var(--color-border)]/50">
                    <td className="py-1.5 px-2 font-mono">v{v.version}</td>
                    <td className="py-1.5 px-2">{v.artifactType}</td>
                    <td className="py-1.5 px-2 text-[var(--color-text-muted)]">{new Date(v.timestamp).toLocaleString()}</td>
                    <td className="py-1.5 px-2">
                      {v.artifactId === artifactId ? (
                        <Badge className="text-xs bg-green-500/10 text-green-400 border border-green-500/20">Active</Badge>
                      ) : (
                        <Badge className="text-xs bg-slate-500/10 text-slate-400 border border-slate-500/20">Historical</Badge>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
